---
apiVersion: v2
name: listener-operator
version: "25.11.0"
appVersion: "25.11.0"
description: The Stackable Operator for Stackable Listener Operator
home: https://github.com/stackabletech/listener-operator
maintainers:
  - name: Stackable
    url: https://www.stackable.tech
